const REPO_URL = 'https://github.com/TinyTank800/MinecraftAllImages';

function GitHubIcon() {
	return (
		<svg className="footer-card-icon-svg" viewBox="0 0 24 24" aria-hidden="true">
			<path
				fill="currentColor"
				d="M12 0C5.37 0 0 5.37 0 12c0 5.31 3.435 9.795 8.205 11.385.6.105.825-.255.825-.57 0-.285-.015-1.23-.015-2.235-3.015.555-3.795-.735-4.035-1.41-.135-.345-.72-1.41-1.23-1.695-.42-.225-1.02-.78-.015-.795.945-.015 1.62.87 1.845 1.23 1.08 1.815 2.805 1.305 3.495.99.105-.78.42-1.305.765-1.605-2.67-.3-5.46-1.335-5.46-5.925 0-1.305.465-2.385 1.23-3.225-.12-.3-.54-1.53.12-3.18 0 0 1.005-.315 3.3 1.23.96-.27 1.98-.405 3-.405s2.04.135 3 .405c2.295-1.56 3.3-1.23 3.3-1.23.66 1.65.24 2.88.12 3.18.765.84 1.23 1.905 1.23 3.225 0 4.605-2.805 5.625-5.475 5.925.435.375.81 1.095.81 2.22 0 1.605-.015 2.895-.015 3.3 0 .315.225.69.825.57A12.02 12.02 0 0 0 24 12c0-6.63-5.37-12-12-12Z"
			/>
		</svg>
	);
}

export function SiteFooter() {
	const year = new Date().getFullYear();

	return (
		<footer className="site-footer">
			<div className="container">
				<div className="footer-cards">
					<a
						className="footer-card"
						href={REPO_URL}
						target="_blank"
						rel="noopener noreferrer"
						aria-label="Open source on GitHub — view repository"
					>
						<div className="footer-card-icon footer-card-icon--github">
							<GitHubIcon />
						</div>
						<span className="footer-card-text">
							<strong>Open Source</strong>
							<span className="footer-card-sub">
								MIT licensed — browse the code, contribute, or report issues on GitHub
							</span>
						</span>
					</a>

					<a
						className="footer-card"
						href="https://okamisquadron.com/"
						target="_blank"
						rel="noopener noreferrer"
						aria-label="Okami Squadron — visit website"
					>
						<img
							src="/assets/okami-squadron-logo.webp"
							alt=""
							width={160}
							height={48}
							className="footer-card-logo"
							loading="lazy"
						/>
						<span className="footer-card-text">
							Made by <strong>Okami Squadron</strong>
							<span className="footer-card-sub">Built for the community, by the community!</span>
						</span>
					</a>
				</div>

				<hr className="border-none h-px site-footer-divider" />

				<p className="text-center text-sm" style={{ color: 'var(--text-muted)' }} suppressHydrationWarning>
					© {year} Okami Squadron · Minecraft Item Gallery
				</p>
				<p className="text-center text-xs mt-2" style={{ color: 'var(--text-muted)' }}>
					Not affiliated with Mojang or Microsoft. Minecraft is a trademark of Mojang AB.
				</p>
				<p className="footer-ai-disclosure-wrap">
					<span className="footer-ai-disclosure" tabIndex={0}>
						AI disclosure
						<span className="footer-ai-disclosure-tip" role="tooltip">
							Parts of this website&apos;s code and documentation were written with AI-assisted
							development tools. Item images are captured in-game with the Fabric export mod — not
							generated by AI.
						</span>
					</span>
				</p>
			</div>
		</footer>
	);
}
